# Generated by Django 3.2.20 on 2023-10-04 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='期日'),
        ),
        migrations.AddField(
            model_name='post',
            name='task',
            field=models.CharField(default=' ', max_length=10, verbose_name='タスク名'),
        ),
    ]
