# Generated by Django 3.2.20 on 2023-10-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
        migrations.AddField(
            model_name='post',
            name='deadlineday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='締切日にち'),
        ),
        migrations.AddField(
            model_name='post',
            name='deadlinetime',
            field=models.TimeField(blank=True, null=True, verbose_name='締切時間'),
        ),
    ]
