# Generated by Django 3.2.20 on 2023-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231011_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadlineday',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deadlinetime',
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='締切日時'),
        ),
    ]
